Documentation:
  Enabled: false
Metrics/LineLength:
    Max: 120
Lint/HandleExceptions:
  Enabled: false

AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - Gemfile
    - db/schema.rb
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - bin/*
