language: ruby
rvm:
  - 2.2.0
env:
  - DB=postgres
bundler_args: --jobs=2
script:
  - bundle exec rake db:setup
  - xvfb-run bundle exec rake
before_script:
  - cp config/database.example.yml config/database.yml
  - psql -c 'create database ff_test;' -U postgres
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"