env:
  global:
    - CC_TEST_REPORTER_ID=84d691b4d99d19825e8bdeef5b10c198625e7e67d8da1c7eeaf9b8d11622b079
language: ruby
rvm:
  - 2.2.0
bundler_args: --jobs=2
script:
  - bundle exec rake db:setup
  - xvfb-run bundle exec rake
before_script:
  - cp config/database.example.yml config/database.yml
  - psql -c 'create database ff_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"